# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b309e24f8d1e1ea013225d215deccee4a0b4c3f674c45d50c755f9185b6b332eee78911c735e3c35f09c80dd76c67adeffe45f11b9c6ea48cbedbed1167e3d2a

test:
  secret_key_base: 24177348735580f8072b0fbfc430080101eb4fc2f109fdd09e2e1e4117e2d92880475d7367958d5ddaad1869f2ba992b9e9a03f62e0463b9783c19f27f7caae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
